### ISSUE TITLE
[FEATURE] The rest of the villagers and NPC shops

### ISSUE THREAD

**Issue by Swofty-Developments** [Swofty-Developments/HypixelSkyBlock#101]
Bit of boilerplate stuff but the rest of the villagers and NPC shops need to be made rather than whats there right now, should also come with missions

**Comment by ItzKatze** [comment]
working on that

**Comment by Epicportal14** [comment]
Done Added Most of the required NPC!

**Comment by ItzKatze** [comment]
> Done Added Most of the required NPC!

i added only the skins and some shop guis, most of the npcs are not functional yet
