### ISSUE TITLE
[BUG] NPC Shops

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#111]
If the amount displayed for an item is greater than one, it only shows the correct amount after buying the item instead of when opening the menu.

![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/76b7468b-5c82-47d0-89e9-695711797a28)
^^Ingame Menu after opening

![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/d9d6ef65-df9b-4370-a0bd-8a7380c47aa0)
^^Ingame Menu after buying each item once

![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/a39eb5be-61e4-47df-8514-f0ce7f7c82b9)
^^Wiki

After closing it, it resets to 1 item per slot.

**Comment by Swofty-Developments** [comment]
Patched in the latest push
