### ISSUE TITLE
[FEATURE] Support Buying Items from Shops with Items

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#113]
Currently you can only buy items from NPC shops with coins. 
Some Items can only be purchased with items. The goal is to support this.

Example:
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/80fdf727-b82d-41d2-8001-a58893759867)
Costs 3 Gold Ingots to buy

**Comment by Swofty-Developments** [comment]
Added in latest push
