### ISSUE TITLE
[BUG] Skill Level Order

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#114]
In each Skill category some levels have a wrong order.

![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/0341b14d-4486-4ad9-89a5-e65938804645)
^^Skill Level 10

![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/4a9b92cf-964b-4005-a150-632cd7e400b5)
^^Skill Level 17, should be 11

**Comment by Swofty-Developments** [comment]
Patched in latest push
