### ISSUE TITLE
[FEATURE] Shortened collection requirements

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#115]
Currently if you need 1000 Coal for a Collectiongoal to unlock it says 1000 coal.
100000 coal needed => it says 100000 coal

This gets messy with large numbers.
Hypixel shortened every number >=1000 with k or m

Goal:
1000 coal => 1k coal
1500000 Gemstones => 1.5m Gemstones

![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/54aba737-a967-4887-8fc7-632f16101dca)
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/58b64b7e-b0e9-4c31-84f7-e1e58e47f6d3)

**Comment by Swofty-Developments** [comment]
Added in latest push
