### ISSUE TITLE
[BUG] Oak planks not disappear after crafted.

### ISSUE THREAD

**Issue by Chalityst** [Swofty-Developments/HypixelSkyBlock#121]
**Describe the bug**
Oak planks not disappear after crafting table.

(Sorry i'm not good at english.)

**To Reproduce**
1. Start server and proxy (Minestom & Velocity)
2. Join server
3. Break oak woods
4. Place oak woods in player inventory to jump to Craft items menu.
5. Place oak woods in Craft items menu. (Get 4 oak planks)
6. Place oak planks for Crafting Table
7. Move output Crafting Table to player inventory.
8. Oak planks not disappear.

**Screenshots**
![Screenshot 2024-03-13 070041](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/59061161/352e2155-23d7-47e9-be7c-2e4fac82e94c)

**Additional context**
- Reinstall MongoDB and Redis.
- Use latest version SkyblockCore and SkyblockProxy

**Comment by Swofty-Developments** [comment]
Patched in the latest push
