### ISSUE TITLE
[BUG] Objective in village not continue.

### ISSUE THREAD

**Issue by Chalityst** [Swofty-Developments/HypixelSkyBlock#123]
**Describe the bug**
Objective in village not continue. If player not right click on NPC

(Sorry i'm not good at english.)

**To Reproduce with screenshot**
1. Use the teleporter to village server.
2. On scoreboard not showing up objective. [BUG]
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/59061161/fd88b10b-8ee0-4899-9480-9a21d0c93161)

3. Right click on NPC
4. Objective on scoreboard showing up and green glowing effect on NPC head.
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/59061161/7dbc26ef-0179-46f0-becc-d5f9f431b610)

**Comment by Swofty-Developments** [comment]
Refer to your other issue [here](https://github.com/Swofty-Developments/HypixelSkyBlock/issues/122)

**Comment by Swofty-Developments** [comment]
Fixed in the latest push
