### ISSUE TITLE
[FEATURE] Missing Minion Features

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#125]
- #96 (Minion Upgrades (Sc3k, Diamond Spreading etc.))
- Minion Fuel
- Minion Storages
- Automated Shipping
- Minion Skins
If you meant all of these above with #96 mb but technically they arent Upgrades https://wiki.hypixel.net/Minions#Minion_Upgrades :)
- Minion Dialogue (Blocked Minion conditions, Minion conversations, specific conditions)

- Prob same as the one above but make the [BLOCKED] in tab more accurate for example Storage is Full
- Make Minions work if they can (currently it stops working if only one block is blocked, normally it should work till every possible block is blocked)
- Havent looked at the code yet but if not already there add support for tree and mob minions

**Comment by Swofty-Developments** [comment]
This is what I meant in my issue, you just described it better
