### ISSUE TITLE
Make recipes with 5 slots into the star form

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#141]
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/829b851a-e8ef-4540-98cf-97784cd66e4c)
now^^
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/48e2a7a7-f7de-4157-b4f6-a55b92ee9adf)
should look like this^^

getStandardEnchantedRecipe() and ShapelessRecipe() should have this

**Comment by Swofty-Developments** [comment]
Working on this currently

**Comment by Swofty-Developments** [comment]
Done in the latest push
