### ISSUE TITLE
[Enhancement] Gemstone Slots

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#142]
- Add support for 3-5 Gemstone slots (currently only 1-2)
- Add support for unlocking Slots with coins (currently there) and coins with items (for example 20 fine ruby)
- If no coins/items are put in, mark the slot as unlocked by default
- Allow for 2 of the same slots, currently it throws an duplicate key error

This kinda has time till dwarven mines but it would safe time so we dont have to adjust some items again

**Comment by Swofty-Developments** [comment]
Hey, there's support for an infinite amount of gemstone slots, I'm unsure where you only found 1-2. The GUI for unlocking however does need to be made aswell as the duplication issue you spoke about

**Comment by Swofty-Developments** [comment]
Fixed in the latest push
