### ISSUE TITLE
Typo in ViewRecipeCommand

### ISSUE THREAD

**Issue by Ghosty920** [Swofty-Developments/HypixelSkyBlock#148]
https://github.com/Swofty-Developments/HypixelSkyBlock/blob/915a6281b39a04899aeeb69ce9fbc942b3963a6c/generic/src/main/java/net/swofty/types/generic/command/commands/ViewRecipeCommand.java#L14
How did I see that? You don't have to ask

**Comment by ItzKatze** [comment]
will be fixed on my next pull request :)
