### ISSUE TITLE
[BUG] Item not appearing well

### ISSUE THREAD

**Issue by Ghosty920** [Swofty-Developments/HypixelSkyBlock#15]
**Describe the bug**
Before holding the item in hand, it will not have any apparence (rip my english)
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/37075355/bcb2af0d-1b09-4a6c-b574-91c036a7f579)
Image is an enchanted book but it also works with hyperion and ig every item
When the item is already in hand, it puts a little delay of like 1 tick before the item is updated

**To Reproduce**
1. Be in another slot than the one where the next item will appear
2. /item hyperion
3. Open inventory and move your mouse on the item

**Comment by Ghosty920** [comment]
PS: Its most probably (i didn't check) how the item nbt system is made, only updating when the weapon is hold to also update at the same time the player stats, as the nbt is missing (7 instead of 8)

**Comment by Swofty-Developments** [comment]
This is also something that occurs on Hypixel, Items do not update unless you log in with them in your inventory or hold them. As a solution to this happening for the `/e` menu we can merely manually run PlayerItemUpdater#update on it and then give that ItemStack to the player.
