### ISSUE TITLE
[FEATURE] Basic stat changes (and mining)

### ISSUE THREAD

**Issue by TreesOnTop** [Swofty-Developments/HypixelSkyBlock#216]
Speed should be capped at 400 by default life should regen over time and the colors of the stats when you hover over "Your Skyblock Profile" should match Hypixels/the colors of the stats in the stats GUI. also not sure if It's just not implemented yet or if it's a bug, but you can't mine in the coal mine because of the mining fatigue and the block breaking amount not changing unless you stand slightly outside the coal mine in the village but mine the stone in the coal mine.

https://github.com/Swofty-Developments/HypixelSkyBlock/assets/85085371/328379ea-111c-4655-95a9-467005531dbd

**Comment by TreesOnTop** [comment]
It also appears that stat bonuses from held items don't work while in the skyblock menu.

https://github.com/Swofty-Developments/HypixelSkyBlock/assets/85085371/aeb45858-c162-4e5b-8b64-76a1adc52568

**Comment by TreesOnTop** [comment]
Also, if you have over 100 health then remove whatever is increasing your max health, your max health will go back down to 100 while your health stays at 100.

https://github.com/Swofty-Developments/HypixelSkyBlock/assets/85085371/3a1776ad-2e4a-40d2-bfcc-14cfa9acc556

**Comment by TreesOnTop** [comment]
also realized that health regen does work but just not in the hub

**Comment by Swofty-Developments** [comment]
Everything has been fixed except for the SB menu
