### ISSUE TITLE
[BUG] NPC shop prices incorrect

### ISSUE THREAD

**Issue by TreesOnTop** [Swofty-Developments/HypixelSkyBlock#217]
Some NPCs have incorrect shop prices, for example the mine merchant sells 2 coal for 8 coins on Hypixel whereas here it costs 8 coins per coal this applies to every item in the mine merchant and possibly other NPCs I that have yet to check.

**Comment by TreesOnTop** [comment]
I checked most of the shops and most have the same issue besides farm merchant, and it can be fixed by just diving the cost by the amount. I also noticed that all items have a limit of 640 items when most are normally unlimited.

**Comment by TreesOnTop** [comment]
incorrect prices fixed by #220

**Comment by ItzKatze** [comment]
actually fixed in #222

**Comment by TreesOnTop** [comment]
basically fixed except for arrows which aren't bought in multiples of 12

**Comment by TreesOnTop** [comment]
nvm this uses integer division when calculating the prices which means that for some items its way cheaper to buy in multiples of 1 than the default value
