### ISSUE TITLE
[BUG] Buying from npcs for free

### ISSUE THREAD

**Issue by TreesOnTop** [Swofty-Developments/HypixelSkyBlock#235]
No clue how it works or what causes it but if you spam left and right click while opening and closing a shop GUI you can occasionally drop the shop item on the floor getting it for free. Other than that, I don't have a way that's easier to replicate.

https://github.com/Swofty-Developments/HypixelSkyBlock/assets/85085371/e76fde9d-2b2e-4935-8061-c50fed1d92ee

**Comment by Swofty-Developments** [comment]
Should be fixed in latest commit
