### ISSUE TITLE
[BUG] dropping bedrock

### ISSUE THREAD

**Issue by TreesOnTop** [Swofty-Developments/HypixelSkyBlock#246]
If you hold q in the shop GUI you'll drop bedrock, I believe this is happening because you try to drop an item that doesn't exist.
https://github.com/Swofty-Developments/HypixelSkyBlock/assets/85085371/a7ad7ea3-269a-49bd-9948-ea1675492ce0

**Comment by Swofty-Developments** [comment]
Resolved in latest commit
