### ISSUE TITLE
Adding json file with data from hypixel API

### ISSUE THREAD

**Issue by treeot** [Swofty-Developments/HypixelSkyBlock#265]
Regarding /wikithis, can I take data from the hypixel api and store/use it in the code?

**Comment by Swofty-Developments** [comment]
Sure! If this were to be implemented, I'd want it to be like HypixelService in the same way that SongService runs, in that it's optional as an option in the resources.json, meaning the `/wikithis` command for example wouldn't work with this option turned off in the same way that the song events don't run if the song service isn't started.

Refs;
[SkyBlockSongHandler](https://github.com/Swofty-Developments/HypixelSkyBlock/blob/d02094b3d2440e7991b755ef1a819970ef65640e/generic/src/main/java/net/swofty/types/generic/noteblock/SkyBlockSongsHandler.java#L21)
[Checks to see if should start service](https://github.com/Swofty-Developments/HypixelSkyBlock/blob/d02094b3d2440e7991b755ef1a819970ef65640e/generic/src/main/java/net/swofty/types/generic/SkyBlockGenericLoader.java#L184)

You can save the result of the search to a file that gets updated on startup if you wish, probably better than using up bandwith
