### ISSUE TITLE
[BUG]Javadocs link is not working

### ISSUE THREAD

**Issue by shuMan3114** [Swofty-Developments/HypixelSkyBlock#33]
The javadocs link in the readme.md redirects to a 404. The javadocs link is mentioned here:
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/40137599/b425e643-54d8-4b2c-8bc2-a2ecf8178984)

**Comment by Swofty-Developments** [comment]
Resolved

**Comment by shuMan3114** [comment]
I can work on the documentation if no one is.

**Comment by Swofty-Developments** [comment]
That would be great if you could.
