### ISSUE TITLE
[BUG] Item dupe

### ISSUE THREAD

**Issue by Ghosty920** [Swofty-Developments/HypixelSkyBlock#37]
**Describe the bug**
Duplicate any item

**To Reproduce**
1. Get an item
2. Open your inventory
3. Get your item in the cursor and click
4. Click out of the inventory to drop it
5. Get back the item from the ground
6. Retry until it's duplicated

The items work and are not ghost items, they can be enchanted, modified, used...

Don't ask how I find that

**Comment by Swofty-Developments** [comment]
Yeah I brought this up to Maploop, there are also alot of glitches with the CraftingGUI. We'll need to figure it out cuz it's pretty important.

**Comment by Swofty-Developments** [comment]
Just pushed a fix to this bug, seems to work well
