### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eevilbird** [Swofty-Developments/HypixelSkyBlock#374]
**Describe the bug**
Discord invite is invalid

**To Reproduce**
1. Click on "Discord"
2. See error

**Expected behavior**
Get discord invite

**Comment by ItzKatze** [comment]
the issue is that swofty used a vanity link which expires if the server looses a level, here is a never link: https://discord.gg/atlas-network-830345347867476000

**Comment by Swofty-Developments** [comment]
I've updated it on the readme
