### ISSUE TITLE
[BUG] This.profileId is null

### ISSUE THREAD

**Issue by Chalityst** [Swofty-Developments/HypixelSkyBlock#38]
**Describe the bug**
java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "this.profileId" is null

(Sorry i'm not good at english.)

**To Reproduce**

1. Package to jar file in Intellij IDEA (Latest Git)
2. Start Mongod (zip version).
3. Put jar package to server folder.
4. Start server (java -jar Skyblock.jar) .bat file
5. Join server (1.20.1)
6. You will get encrypting... loading stuck and timeout.
7. Error in console "java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "this.profileId" is null"

**Screenshots**
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/59061161/ba12b146-ba21-48ba-838b-97c31a007f43)

**Comment by Ghosty920** [comment]
Do you use a cracked version of Minecraft?

**Comment by Chalityst** [comment]
> Do you use a cracked version of Minecraft?

For launcher : yes but premium account. (legit and mitigated to microsoft account)
Before (Start of profile support) Commits, I can join to server normally.

**Comment by Ghosty920** [comment]
Oh then it's probably just from the code, not the minecraft session, should have thinked abt it first

**Comment by Chalityst** [comment]
> Oh then it's probably just from the code, not the minecraft session, should have thinked abt it first

Thank you for your response.
I tried to use minecraft launcher from minecraft.net and yeah still not working ("this.profileId" is null).

**Comment by Swofty-Developments** [comment]
I have pushed a fix to the repository, please re-download the .JAR from the Releases tab and tell me if it works.

**Comment by Chalityst** [comment]
> I have pushed a fix to the repository, please re-download the .JAR from the Releases tab and tell me if it works.

Latest repository fixed. Problem solved.
Thank you so much!
