### ISSUE TITLE
[BUG] Could not find or load main class

### ISSUE THREAD

**Issue by Chalityst** [Swofty-Developments/HypixelSkyBlock#46]
**Describe the bug**
Could not find or load main class net.swofty.loader.skyblock

(Sorry i'm not good at english.)

**To Reproduce**
1. Download SkyblockCore and SkyblockProxy (Shaded) from github
2. Start Mongod (zip version) with cmd (mongod -dbpath C:\MongoDB\data)
3. Start SkyblockCore with cmd ("jdk-17 path\bin\java" -jar Skyblock.jar ISLAND)
4. Error on console
`Error: Could not find or load main class net.swofty.loader.skyblock
Caused by: java.lang.CLassNotFoundException: net.swofty.loader.skyblock`

**Screenshots**
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/59061161/ec8a07c5-2c65-4ff3-a0d2-6814a96db5f9)

**Additional context**
- I do anything and complete with setup guide on readme github.
- Clean install, Removed all folder except jar file.
- Installed redis (memurai)

**Comment by Swofty-Developments** [comment]
Hey, I've been able to replicate your issue and have fixed it with the latest push. You can download the new SkyBlockCore from [here](https://github.com/Swofty-Developments/HypixelSkyBlock/releases/tag/latest).
