### ISSUE TITLE
[BUG] Item dupe using inventory craft grid (2x2)

### ISSUE THREAD

**Issue by lolo45654** [Swofty-Developments/HypixelSkyBlock#55]
**Describe the bug**
Consistent item dupe which creates an item that has the same nbt and amount of the first item using the inventory craft grid and hotkeying (1-9) the hotbar items to that grid.
Any item seems to work, except the SkyBlock Menu. (which won't open the custom craft gui)

**To Reproduce**
1. Get any item. (ex. "/item ENCHANTED_DIAMOND_BLOCK")
2. Open your inventory.
3. Hotkey the just received item into the grid.
    If your first hotbar slot key is 1, and the item is in the first hotbar slot, you would hover over any of the 2x2 slots of the crafting grid (NOT the result slot) and press 1
5. The custom crafting gui opens and you have double the amount of that item.

**Expected behavior**
The custom crafting gui should open without you having duped the item.

**Screenshots**
![the inventory craft grid](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/67123979/098dc280-0e6b-4467-8d39-bbe5aa5ca658)

**Additional context**
I am using the latest version.

**Comment by Swofty-Developments** [comment]
Currently looking into it

**Comment by Swofty-Developments** [comment]
Issue has been fixed
