### ISSUE TITLE
[BUG] Hotkeying items into Shop GUI will dupe them.

### ISSUE THREAD

**Issue by lolo45654** [Swofty-Developments/HypixelSkyBlock#62]
**Describe the bug**
If you hotkey/numkey an item from your hotbar to a buyable shop item, you will buy the shop item and double the hotkeyed item.

**To Reproduce**
1. Get an item. (`/item ENCHANTED_DIAMOND_BLOCK`)
2. Do `/testopenshopgui`
3. Hotkey the item to one of the buyable shop items.

**Expected behavior**
Buy the shop item and not dupe.

**Screenshots**

**Additional context**

**Comment by Swofty-Developments** [comment]
Has been fixed in latest push
