### ISSUE TITLE
[BUG] Item dupe in Reforge GUI

### ISSUE THREAD

**Issue by lolo45654** [Swofty-Developments/HypixelSkyBlock#63]
**Describe the bug**
Quickly taking out an item and putting it back will result in duping the item. This only happens in the Reforge GUI, not in the Enchanting GUI.

**To Reproduce**
1. Place an item in the Reforge GUI.
2. Double click it.
3. There will now be an item on your cursor, and in the slot.

**Expected behavior**
The item should only be on the cursor, due to the vanilla item move cooldown.

**Screenshots**

https://github.com/Swofty-Developments/HypixelSkyBlock/assets/67123979/7e52595e-a0dc-4f88-93a6-8555b1482017

**Comment by Swofty-Developments** [comment]
Has been fixed in latest push
