### ISSUE TITLE
[BUG] Village Server FO: Loading player data for setEnv ... java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by tinywifi** [Swofty-Developments/HypixelSkyBlock#83]
**Describe the bug**
When I tried to go to the village by going through the portal my minecraft got stuck at Downloading terrain and when I check the village  cmd it showed 

2024-03-03 13:38:11 [Ms-worker-1] net.swofty.types.generic.SkyBlockGenericLoader.lambda$initialize$16() INFO: Received new player: setEnv (f0a534f0-94f9-4ab4-bc39-ee7ecf6b7e9f)
2024-03-03 13:38:11 [ForkJoinPool.commonPool-worker-11] net.swofty.types.generic.event.actions.player.data.ActionPlayerDataLoad.run() INFO: New player joined: setEnv...
2024-03-03 13:38:14 [Ms-TickScheduler] net.swofty.types.generic.event.actions.player.data.ActionPlayerDataSpawn.run() INFO: Loading player data for setEnv...
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

**To Reproduce**
1. Start the server like intended
2. Try to go into the hub portal from your island
3. See error

**Expected behavior**
I should be able to go to the hub

**Screenshots**
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/65711396/abd1659e-7373-4ff8-bede-dd4708d11ea0)

![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/65711396/1cee7895-6a6e-438c-ad20-ff3e8fecb822)

**Additional context**
-

**Comment by Swofty-Developments** [comment]
I predict this is an issue relating to a lack of checks surrounding null-regions. Have you imported the Regions csv as described in the instructions?

**Comment by tinywifi** [comment]
its added 
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/65711396/9ba2dedb-9256-4cbc-8f93-6ab9bfd6a239)


also I got a question how do i add myself as admin? I checked but i cant bother editing the adminme command

**Comment by tinywifi** [comment]
nvm i found out the problem now. i missed spell minestom but i still have question about adding myself as admin

**Comment by tinywifi** [comment]
nvm i modified minestorm.data
