### ISSUE TITLE
Modify how the Held Item for Minions work

### ISSUE THREAD

**Issue by Ghosty920** [Swofty-Developments/HypixelSkyBlock#89]
Normally, in SkyBlock, when upgrading some minions, their held item change, from for example a Wooden Pickaxe to a Stone Pickaxe

In [net.swofty.types.generic.minion.SkyBlockMinion.MinionTier](https://github.com/Swofty-Developments/HypixelSkyBlock/blob/eec3e6b020635b8f85ae5bf8b3855de7d13d7324/generic/src/main/java/net/swofty/types/generic/minion/SkyBlockMinion.java#L19), maybe add a parameter to the constructor being a `Material`, instead of using [`getHeldItem()`](https://github.com/Swofty-Developments/HypixelSkyBlock/blob/eec3e6b020635b8f85ae5bf8b3855de7d13d7324/generic/src/main/java/net/swofty/types/generic/minion/SkyBlockMinion.java#L15)

Cobblestone Minion V
![image1](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/37075355/b113d7a9-cfab-4606-87aa-b84d0aa9cb77)

Cobblestone Minion XI
![image2](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/37075355/9a6349c6-283f-422b-a27f-7c0750569f67)

**Comment by Swofty-Developments** [comment]
Oh I didn’t know that, easy implementation though

**Comment by Swofty-Developments** [comment]
[Implemented](https://github.com/Swofty-Developments/HypixelSkyBlock/commit/ac3b013a7753700a76242954ac17d1e2027ab3a7)
