### ISSUE TITLE
[Small Correction] Unlocking a Skill

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#91]
After unlocking farming it says: SKILL LEVEL UP Farming 0>I
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/4b72729b-6477-4a01-9e9a-70609f61c954)
instead of: SKILL LEVEL UP Farming I
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/86bc23c8-9a65-4068-b54a-bedcf26ddac5)

basically remove 0> if oldLevel = 0

**Comment by Swofty-Developments** [comment]
Fixed
