### ISSUE TITLE
[Suggestion] Enchanted Item Crafting System

### ISSUE THREAD

**Issue by ItzKatze** [Swofty-Developments/HypixelSkyBlock#93]
Right now only 1 Crafting recipe is supported for enchanted materials.
In Skyblock there are cases where 1 item could have multiple recipes and/or use 2 or more kinds of items.

Example 1: 
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/841d138a-5f3b-4c02-9dc5-03218685e239)
Enchanted Emeralds can be crafted using normal emeralds or emerald blocks.

Example 2:
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/c167c830-268c-4cf8-95bb-824760cd9511)
Enchanted Charcoal is crafted using 128 coal and 32 oak wood.

Example 3:
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/4e968029-bddd-463b-b890-de9c6ce72b37)
Enchanted Fermented Spider Eyes are being crafted using 3 stacks of differant Materials.

Example 4:
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/77b4c71e-bfa8-4de1-bc6f-39419668d208)
Enchanted Bread is crafted using 60 Wheat.

Example 5:
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/136186750/f95be5ea-c201-445f-bf96-3ef8e3dbd806)
Enchanted Ender Pearls use 20 normal pearls.

This issue should be a suggestion for a system that supports these cases and more if I missed some.

**Comment by Swofty-Developments** [comment]
Hey, the recipe system does actually allow for multi-recipes already. So you can see, I've implemented your emerald block recipe [here](https://github.com/Swofty-Developments/HypixelSkyBlock/blob/e237bd2ed5e77021caaad2edef4a5aa87d40c044/generic/src/main/java/net/swofty/types/generic/item/items/enchanted/EnchantedEmerald.java).
